### ISSUE TITLE
fails: node generate.js -v usfm_asvsf

### ISSUE THREAD

**Issue by noriz** [digitalbiblesociety/browserbible-3#58]
Hi !

Just qwesome work on the browserbible :-) I appreciate your efforts and was surprised to 
find the aramaic Peshitta Bible so easily installed using the node.js system you built.

I am currently trying to get the King James Strongs to work. I cloned the repository 
, compiled KJV, added a Norwegina bible - all well, but once I try to compile anything 
with usfm, like even the pre-existing ones it fails. I cant compile usfm_asvsf or usfm_asvsf. 
The message I get is the same:

"Can't find: usfm"

Thanks !
Jørn Andre

**Comment by barryanders** [comment]
I was going to try and help you, but it does appear to be true from my end as well. With the latest updates from GitHub, "generator: usfm" doesn't output the files in the content/texts directory. Instead of an error, mine just gets skipped, noriz. Assuming that the usfm generator is finished, it's probably a minor thing.

**Comment by johndyer** [comment]
Do you have this file?
https://github.com/digitalbiblesociety/browserbible-3/blob/master/tools/textgenerator/node_modules/generate_usfm.js

On Tue, Feb 3, 2015 at 2:07 PM, Barry <notifications@github.com> wrote:

> I was going to try and help you, but it does appear to be true from my end
> as well. With the latest updates from GitHub, "generator: usfm" doesn't
> output the files in the content/texts directory. Instead of an error, mine
> just gets skipped, noriz. Assuming that the usfm generator is finished,
> it's probably a minor thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalbiblesociety/browserbible-3/issues/58#issuecomment-72724071>
> .
>



-- 
John Dyer - http://j.hn/

**Comment by noriz** [comment]
Hi John !

No, I didnt. On my ipad right now and tried though, but it failed
generating. Might be something I did. Will try when I get back
home. I am getting syntax error on first line, which indicates a
basic fail on my part :-)

Thanks !
Jørn Andre

On Wednesday, February 4, 2015, John Dyer <notifications@github.com> wrote:

> Do you have this file?
>
> https://github.com/digitalbiblesociety/browserbible-3/blob/master/tools/textgenerator/node_modules/generate_usfm.js
>
> On Tue, Feb 3, 2015 at 2:07 PM, Barry <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I was going to try and help you, but it does appear to be true from my
> end
> > as well. With the latest updates from GitHub, "generator: usfm" doesn't
> > output the files in the content/texts directory. Instead of an error,
> mine
> > just gets skipped, noriz. Assuming that the usfm generator is finished,
> > it's probably a minor thing.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/digitalbiblesociety/browserbible-3/issues/58#issuecomment-72724071
> >
> > .
> >
>
>
>
> --
> John Dyer - http://j.hn/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalbiblesociety/browserbible-3/issues/58#issuecomment-72779954>
> .
>


-- 
Sendt fra Gmail for mobil

**Comment by barryanders** [comment]
I do have it. Here's my output from generating all. There appears to be more that it's not finding, but I'm not sure why its not finding it when I've got the generate_X.js files in the node_modules folder. Is it just a directory mistake in code, or perhaps something I did wrong? I just have the repo cloned and I followed the guide.

When I was using this actively before and did some spelling/whitespace cleanup for it several months ago, I noticed that certain texts wouldn't generate properly. I never really payed attention to the preinstalled ones though. Still, this is to be expected, since they may not all follow the exact format.

```-----
Treasury of Scripture Knowledge (Enhanced) ../../app/content/texts/comm_eng_tske
[==================================================] [30594/30594] 75.9
processText: 77143ms
outputFiles: 3168ms
Copying stylesheet input/com_tske/style.css ../../app/content/texts/comm_eng_tske/style.css
-time: 0000:01:20.65
-----
Wescott & Hort ../../app/content/texts/grc_wh

[==================================================] [7970/7970] 0.5
processText: 601ms
outputFiles: 249ms
-time: 0000:00:00.97
Can't find: osis
-----
King James Version ../../app/content/texts/eng_kjv

[==================================================] [37112/37112] 2.9
processText: 3023ms
outputFiles: 798ms
-time: 0000:00:04.28
-----
SBL Greek New Testament ../../app/content/texts/grc_sblgnt

[============================================------] [27/31] 1.3processText: 1561ms
outputFiles: 357ms
-time: 0000:00:02.05
Can't find: usfm
Can't find: usfm
Can't find: morphhb
-----
Young's Literal Translation ../../app/content/texts/eng_ylt

[==================================================] [31115/31115] 2.0
processText: 2180ms
outputFiles: 783ms
-time: 0000:00:03.79
TOTAL: 0000:01:33.29```

**Comment by noriz** [comment]
Hi again !

When I try to generate the bible using a pre-existing bible in
browserbible-3 I get this

$ node generate_usfm.js usfm_asvsf

/home/bible/browserbible-3/tools/textgenerator/generate_usfm.js:9
$ = require('jquery')(jsdom.jsdom().createWindow()),
                                    ^
TypeError: Object [object HTMLDocument] has no method 'createWindow'
    at Object.<anonymous>
(/home/bible/browserbible-3/tools/textgenerator/generate_usfm.js:9:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

When I clone browserbible-3.git it does not include the generate_usms.js

Thanks !
Jørn Andre



2015-02-04 3:37 GMT+01:00 John Dyer <notifications@github.com>:

> Do you have this file?
>
> https://github.com/digitalbiblesociety/browserbible-3/blob/master/tools/textgenerator/node_modules/generate_usfm.js
>
>

**Comment by noriz** [comment]
Hi Again !

Sorry about the last email. I downloaded genrate_usfm.js to the
textgenerator folder
instead of checking the node_modules. I am curently in the node_modules
folder
now, yet it gives me the same error:

 node ./generate_usfm.js usfm_websf

/home/bible/browserbible-3/tools/textgenerator/node_modules/generate_usfm.js:9
$ = require('jquery')(jsdom.jsdom().createWindow()),
                                    ^
TypeError: Object [object HTMLDocument] has no method 'createWindow'
    at Object.<anonymous>
(/home/bible/browserbible-3/tools/textgenerator/node_modules/generate_usfm.js:9:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

I will change machine / another distribution of linux and try again. Might
be Ubuntu 14.10 that is failing.

Thanks !


2015-02-05 5:20 GMT+01:00 Barry <notifications@github.com>:

**Comment by noriz** [comment]
Hi !

When I have installed node and done a freshly clone of browserbible-3 on
raspberry pie I (ARM) still get error trying to generate:

jorn@pi:~/repos/browserbible-3/tools/textgenerator/node_modules$ node
generate_usfm.js usfm_websf

module.js:340
    throw err;
          ^
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>
(/home/jorn/repos/browserbible-3/tools/textgenerator/node_modules/generate_usfm.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
jorn@pi:~/repos/browserbible-3/tools/textgenerator/node_modules$


Thanks !

2015-02-03 20:07 GMT, Barry <notifications@github.com>:

**Comment by barryanders** [comment]
I'm gonna take a swing at this and suggest that the generate_usfm.js file is not intended to be ran directly, but rather, it is used by generate.js to understand the usfm format when processing a usfm text in the input folder.

**Comment by noriz** [comment]
I have just removed a couple of my own messages in this thread since it had nothing to do with the usfm generation. I forgot to run "sudo npm instal" in order to get the dependencies right. 

barryanders - I think you are correct.
johndyer - I do have the node_modules/generate_usfm.js file. I still get the same error though.

$ node generate.js -v kjvs
$ Can't find: usfm

**Comment by johndyer** [comment]
I've only tested the generation on a Mac. I'm wondering if you're on a PC
and the path names are wrong...

On Thu, Feb 5, 2015 at 12:02 PM, Jørn Andre Halseth <
notifications@github.com> wrote:

> I have just removed a couple of my own messages in this thread since it
> had nothing to do with the usfm generation. I forgot to run "sudo npm
> instal" in order to get the dependencies right.
>
> barryanders - I think you are correct.
> johndyer - I do have the node_modules/generate_usfm.js file. I still get
> the same error though.
>
> $ node generate.js -v kjvs
> $ Can't find: usfm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalbiblesociety/browserbible-3/issues/58#issuecomment-73094680>
> .
>



-- 
John Dyer - http://j.hn/

**Comment by barryanders** [comment]
I'm on a mac. I added console.log(ex) to see what error was showing and here's the output: ```[TypeError: Object [object HTMLDocument] has no method 'createWindow']```

Does that have anything to do with the line where that is defined in generate_usfm?

```$ = require('jquery')(jsdom.jsdom().createWindow()),```

**Comment by noriz** [comment]
Hi johndyer ! 

I cloned the repository on my mac mini and I got the same results as yesterday with Ubuntu (x86):

npm install
npm WARN package.json browserbible_generator@0.0.1 No repository field.
npm WARN package.json browserbible_generator@0.0.1 No README data
Jrns-Mac-mini:textgenerator jornandrehalseth$ node generate.js -a

-----
Treasury of Scripture Knowledge (Enhanced) ../../app/content/texts/comm_eng_tske
[==================================================] [30594/30594] 62.9
processText: 63543ms
outputFiles: 1966ms
Copying stylesheet input/com_tske/style.css ../../app/content/texts/comm_eng_tske/style.css
-time: 0000:01:05.64
-----
Wescott & Hort ../../app/content/texts/grc_wh

[==================================================] [7970/7970] 0.4
processText: 447ms
outputFiles: 501ms
-time: 0000:00:01.00
Can't find: osis
-----
King James Version ../../app/content/texts/eng_kjv

[==================================================] [37112/37112] 2.3
processText: 2312ms
outputFiles: 2386ms
-time: 0000:00:04.80
-----
SBL Greek New Testament ../../app/content/texts/grc_sblgnt

[============================================------] [27/31] 1.2processText: 1447ms
outputFiles: 548ms
-time: 0000:00:02.21
Can't find: usfm
Can't find: usfm
Can't find: morphhb
-----
Young's Literal Translation ../../app/content/texts/eng_ylt

[==================================================] [31115/31115] 2.0
processText: 1998ms
outputFiles: 1755ms
-time: 0000:00:03.87
TOTAL: 0000:01:17.85

Thanks !

**Comment by githubber** [comment]
Hello,
Was this ever solved? I have the same problem.

**Comment by johndyer** [comment]
Shane,
We've just reorganized the generators. Give it another shot now.

On Thu, Mar 17, 2016 at 5:10 AM, Shane Cooke <notifications@github.com>
wrote:

> Hello,
> Was this ever solved? I have the same problem.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalbiblesociety/browserbible-3/issues/58#issuecomment-197801869>
>



-- 
John Dyer - http://j.hn/

**Comment by githubber** [comment]
Yeah, it works now, and the Arabic displays properly. I am testing it now on some bible downloaded from the Unbound Bible site, and tweaked the respective info.json files, but am getting this error. Something tells me I need to choose a different generator (did choose "unbound"), but what are the options for that?
